### ISSUE TITLE
Kész

### ISSUE THREAD

**Issue by krisztikelemen** [Teaching-projects/SOE-ProgAlap2-2021-Beadando-Game-of-life#1]

**Comment by hegyhati** [comment]
No, meglestem, rendben van, bar par dolgot mashogy oldanek meg, de nem ebben a ket napban fogunk ezen agyalni.

No, en szeretnek negyest adni, de kilora ez meg azert nem sok. Par aprosaggal jo volna megpimpelni:

- [ ] a buttonok legyenek negyzet alakuak
- [x]  A reset mellett legyen egy spinbox vagy valami, amivel be lehet allitani a meretet, amire resetel.
- [x] lehessen kimenteni / betolteni valami alakzatot
- [x] lehessen gombbal elore leptetni a dolgot, ne csak elinditani, meg leallitani
- [ ] visszafele lepteteshez mar meg kell jegyezni dolgokat, de akar lehetne egy csuszka is, amit huz az ember, ami egy ilyen timeline

Na ez igy egyutt nyilvan sok, ezek kozott van 2 perces (elso), meg sok munkat igenylo (utolso). Szoval mindet nem, de mondjuk pl az utolsot leszamitva a tobbit meg tudnad/akarod csinalni?

**Comment by hegyhati** [comment]
👍🏻 4
